"""personalization profiles

Revision ID: 7629cbba2b27
Revises: d8a247eaaee4
Create Date: 2026-07-16 12:23:17.851557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7629cbba2b27'
down_revision: Union[str, None] = 'd8a247eaaee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalization_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=16), nullable=False),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personalization_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personalization_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personalization_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personalization_profiles_user_id'))

    op.drop_table('personalization_profiles')
    # ### end Alembic commands ###
