"""initial schema

Revision ID: 8ce8689bada3
Revises: 
Create Date: 2026-07-16 12:01:33.357213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce8689bada3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('github_id', sa.String(length=64), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=False),
    sa.Column('embedding_provider', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=False)

    op.create_table('provider_credentials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('repositories',
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('clone_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('readme_summary', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repositories_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repositories_status'), ['status'], unique=False)

    op.create_table('conversations',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_repository_id'), ['repository_id'], unique=False)

    op.create_table('index_jobs',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_jobs_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_index_jobs_status'), ['status'], unique=False)

    op.create_table('issues',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('github_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('html_url', sa.String(length=512), nullable=False),
    sa.Column('github_created_at', sa.String(length=64), nullable=True),
    sa.Column('github_updated_at', sa.String(length=64), nullable=True),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('complexity_score', sa.Integer(), nullable=True),
    sa.Column('complexity_level', sa.String(length=16), nullable=True),
    sa.Column('estimated_hours', sa.String(length=32), nullable=True),
    sa.Column('suitability_score', sa.Integer(), nullable=True),
    sa.Column('affected_files', sa.Text(), nullable=True),
    sa.Column('required_knowledge', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('analysis_provider', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_number', name='uq_repo_issue')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_github_number'), ['github_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_repository_id'), ['repository_id'], unique=False)

    op.create_table('contribution_tasks',
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('is_safe_category', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('proposed_changes', sa.Text(), nullable=True),
    sa.Column('test_plan', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('confidence_rationale', sa.Text(), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('pr_title', sa.String(length=512), nullable=True),
    sa.Column('pr_body', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('pr_head_repo', sa.String(length=255), nullable=True),
    sa.Column('publish_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contribution_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contribution_tasks_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_tasks_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contribution_tasks_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('contribution_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contribution_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_contribution_tasks_repository_id'))
        batch_op.drop_index(batch_op.f('ix_contribution_tasks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contribution_tasks_issue_id'))

    op.drop_table('contribution_tasks')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_repository_id'))
        batch_op.drop_index(batch_op.f('ix_issues_github_number'))

    op.drop_table('issues')
    with op.batch_alter_table('index_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_index_jobs_repository_id'))

    op.drop_table('index_jobs')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_repository_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repositories_status'))
        batch_op.drop_index(batch_op.f('ix_repositories_owner_id'))
        batch_op.drop_index(batch_op.f('ix_repositories_full_name'))

    op.drop_table('repositories')
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_credentials_user_id'))

    op.drop_table('provider_credentials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_login'))

    op.drop_table('users')
    # ### end Alembic commands ###
