"""github app installations

Revision ID: d8a247eaaee4
Revises: 8ce8689bada3
Create Date: 2026-07-16 12:11:23.330697
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a247eaaee4'
down_revision: Union[str, None] = '8ce8689bada3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('repository_selection', sa.String(length=16), nullable=True),
    sa.Column('sender_login', sa.String(length=255), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_installations_account_login'), ['account_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_installations_installation_id'), ['installation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_github_installations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_installations_user_id'))
        batch_op.drop_index(batch_op.f('ix_github_installations_installation_id'))
        batch_op.drop_index(batch_op.f('ix_github_installations_account_login'))

    op.drop_table('github_installations')
    # ### end Alembic commands ###
